### ISSUE TITLE
Smart Logic to Implement Safety Considerations? 

### ISSUE THREAD

**Issue by shawn0x1** [FinalGravityBrewing/control_panel#4]
@rlmcpherson @ryho @GOFmugsy,  Does anybody know C/C++ and/or Python?  We could just port the brewtroller to an arduino or utilize brewpi's code and port to raspberry pi to simplify the analog circuitry and will also allow us to implement something like a [safe start interlock](http://www.theelectricbrewery.com/control-panel-safe-start-interlock) easily.  

Reasoning:  we want 4 elements on this control panel but only want 2 to be allowed to operate at a time due to current constraints at the panel.  We can accomplish this by utilizing a safe start interlock or use the brewtroller or brewpi.  I know the brewtroller well, but am open to other ideas.  It also has built in PID for heating elements and we could source most parts from [automation  direct](https://www.automationdirect.com/adc/Home/Home),  [auber instruments](http://auberins.com/), and [adafruit](https://www.adafruit.com/).  

Creating this thread to discuss those options, so please weigh in.

**Comment by ryho** [comment]
I'm a software developer, I can handle whatever software we need on RaspPi. I started college as electrical, but only know enough to be dangerous.

What all needs to be done? I'm looking at the smart safe interlock that you link to. I don't think you'll be able to implement that with a RaspPi, because you won't be able to connect the 120V/240V that its controlling to the RaspPi unless you get some 5V/120V relays to allow the circuits to be controlled by the 5V of the RaspPi, and those will cost roughly as much as the interlock parts you're trying to replace.

After looking over it all, it seems that the electric brewery system and the BrewTroller system are essentially not very compatible. All the components, including switches and lights, in the electric brewery system are running at 120V (which seems wild to me, but I'm used to playing with 5V). The BrewTroller is running the control system at 12V with relays between the 12V control system and the 120V/240V appliances. If you try to mix the two systems, the extra relays are going to make it not worth the effort.

**Comment by shawn0x1** [comment]
@ryho , correct, one uses control voltages passed to relays where the other uses the actual voltages.  The previous (gas) control panel I designed used a hybrid of both.  I was planning on using a  [5-32VDC power supply](https://www.amazon.com/gp/product/B00BXAM694/ref=oh_aui_search_detailpage?ie=UTF8&psc=1) to supply any control voltages we may need through the switches to relays sized appropriately for our loads (variation of Electric brewery implementation) if we were to go the Electric Brewery route.  This is how I implemented the sparge control on the water pump.  I passed 5VDC through the float switch to a relay that controlled the water pump.     

For this effort  we can go either the electric brewery (with some 5-32VDC control voltages) and route with a safe start interlock OR go the brewtroller/RasPi route and use control voltages passed through switches.   For instance, switches would be routed to the relays via the RasPi/Brewtroller as digital inputs to the RasPi and digital outputs to the relays to safestart the heating elements.  The code may look something like below (but much better haha):

```python
#safe start, only let two elements on at a time
if (element_switch_a = 1) and (element_switch_b = 1) and (element_switch_c != 1) and (element_switch_d != 1):
 safe_start = 1 # this would control some digital out logic to the relays associated with the switches
```
Forgive my horrible python coding and we would of course need more code to properly implement the safe start, but further developing a code base (already provided by brewtroller - written in C/C++ or brewpi written in python) would be the effort required.

**Comment by shawn0x1** [comment]
Switching this to issue #6.
