### ISSUE TITLE
Wart Hog EBC-350

### ISSUE THREAD

**Issue by ryho** [FinalGravityBrewing/control_panel#5]
@shawn0x1 Have you seen this control panel? It doesn't have quite as many bells and whistles as the electric brewery one, but it's got temp monitoring of the mash and the HLT, controls two pumps, and it can do two both elements at the same time. Its a lot cheaper than the electric brewery pre-built kits
https://www.highgravitybrew.com/store/pc/Brewery-Controller-Electric-Wort-Hog-EBC-350-p5044.htm

**Comment by shawn0x1** [comment]
@ryho, I have, but we are boiling 30+ gallons at a time, which I think will require 2 heating elements per kettle, making it a total of 4 elements (due to the heating time discussion mentioned in issue #1) the control panel will have to drive.  We were going to save the extra cost of the electric brewery kit by building it ourselves, unless you guys want to go with the Wort Hog?

**Comment by rlmcpherson** [comment]
Do we have an estimate of how much the DIY electric brewery will cost (I assume we are not buying their kit)? The Wort Hog does look like it would meet most of our requirements and would reduce the time commitment to build this thing. Probably worth doing a comparison at least.

**Comment by skeptonomicon** [comment]
I am concerned with the control on the heating elements. There should be two each the the HLT and BK. With any kind of reasonable electric service you can only run 2 of the 4 at one time. There are 4 states, 1) off, 2) 2 HLT heaters  3) one HLT and one BK 4) 2 two BK. What ever controller you decide on will have to know not to run both BK and one HLT during the sparge.
The other thing to evaluate is how hard it will be to add manual overrides.
The custom route allows for future tweeking, additions, and any special interlocks or safty features you want to add.

**Comment by shawn0x1** [comment]
I'll put up a schematic and parts list of what I am thinking - basically use a 3-32VDC power supply into 3 position switches for the manual override of pumps, HLT element (with safety start provided by a $35 raspberry pi with the states @skeptonomicon mentioned), Boil Element (with safety start provided by a $35 raspberry pi with the states @skeptonomicon mentioned), and the sparge level control which will have a 3.3VDC control signal going through a float switch monitored by the RPi that turns on a water pump for sparging.  I also have major reservations with the wort hog.  we will have to manually unplug and plug in elements, it does not support more than 2 heating elements, has not auto-sparge control, and will offer no versatility for the future.  I have verbal commitments from @ryho and @skeptonomicon on the python coding portion. let us know if you want to get in on the python @GOFmugsy.  @GOFmugsy, @wgr6, and maybe @rlmcpherson for wiring which includes making cables.  So, if nobody has any complaints with this I say we move over to issue #1 for the parts list and schematic.

**Comment by skeptonomicon** [comment]
I will add that I looked at the video they had, and saw:

1. I am concerned with the stability of the temp loop on the mash tun. I am concerned it may cycle between over and under shoot. I would like to know where the sensors are.
2. They regulate the sparge flow by controlling the flow to the inlet of the pump. This is a big no-no as it causes cavitation and will severely limit the life of the pump. This is not really a feature of the controller, but rather of their personal system they had in the video. It gives me reservation however that they know what they are doing.
3. They talk about having proportional control, but then they regulate the mash using the binary pump control, which defeats the proportional control in the most sensitive part of the brew.
4. As already mentioned, they switch heating elements by manually switching the plugs. I guess they saved the cost on one relay.

**Comment by skeptonomicon** [comment]
I also like the idea of one central PI that controls everything (diplay, controls, pumps, and sensors). It might actually be simpler that way.

**Comment by skeptonomicon** [comment]
OK, I am starting the GUI. This is what I am thinking of, but could be off base on a number of assumptions. It starts with a description of the hardware and continues with a description of the GUI.


HGBrew, a brew controller

construction Notes:
This tkinter GUI implements a 50 gal HERMS brewing system.
 the Herms system consists of three kettles, a HLT, MT, and BK
 There are two heating elements each in the HLT and BK, however due to
   50 Amp breakers, only two total heaters can be run at once
 There are two pumps, one on the HLT heat exchanger, and one on the MT
 pump 1 goes from either MT drain(mashing) or HLT drain(sparging/mash in) 
     to the coil input
 coil output goes to MT sparge arm
 pump 2 goes from  MT drain (sparging) or BK drain (racking) to
    BK(sparging) or counter flow heat exchanger/oxigenator (racking)
 counter flow heat exchanger/oxigenator comes from 2nd pump and goes to fermenter
 There are temp sensors on the coil input & output, MT, HLT, BK
 Herms coil flow will be controlled via electronic valve  which will be
     either on/off or proportional
pump inputs and outputs will be selected by either electronic or manual
    selector valve
pumps will have output preasure switches to warn when cavitaion occurs and
     bleeding/ priming is required.
all activators from computer will have off/on/auto mechanical selector switch
there will be a large red ESTOP (emergency stop) switch
 controls will initially be mouse, but later touchscreen support will be added
 the screen will contain tabs for different control groups:
    timers - there will be several timers/alrams
        mash schedule will have several alarms expressed both as 
        time from start and time to end of mash
    process display - a large state indicator
         (heat up/mash in/mash/sparge/boil/hop rest(s)/racking)
         animated displays indicating pump activation/ heating/ liquid flows
        state controls - buttons that switch between states
        control parameters - set temps, etc.
    graph screen - shows graph of all brewing parameters vs time
    notes - scratch pad for taking brew notes.
    settings - display/set configurations
the screen will have a menu bar at the top for file/plot options/help

the control computer (which runs this GUI) will have battery backup

**Comment by ryho** [comment]
Ok, yeah that doesn't meet all of our needs then. I was just looking around at what the options are since the cost of the panel seems like a huge chunk of the budget. Looks like that's how it these panels go though. Controlling 240v is expensive no matter how you slice it.
